Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2016
Var
numero : inteiro

Inicio
// atribuir um valor para uma variavel usa-se o comando leia(VARIAVEL)
// no exemplo quero um atribuir para a variável numero um valor digitado pelo
// usuário
// para guardar este valor digitado uso o comando leia (pegar o input)

escreval("Digite um número:")
leia(numero)

escreva("O número digitado é: ", numero)

//perceba que posso mostrar o valor de uma várivel com o escreva ou escreval
// usando uma vírgula no fim


Fimalgoritmo
