Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor    : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2016
Var

   i : inteiro

Inicio

   // outro laço
   // enquanto faca fimenquanto
   i<-0

   enquanto (i < 10) faca
      i<-i+1
      escreval("Valor de i: ", i)
   fimenquanto


Fimalgoritmo
