Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor    : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2016
Var
  opcao : caracter

Inicio

// limpatela vai limpar qualquer texto na tela

escreval("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
escreval("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB")
escreval("Gostaria de limpar a tela? s ou n")
leia(opcao)

escolha (opcao)
caso "s"
limpatela
outrocaso
escreval("Você escolheu n")
fimescolha

Fimalgoritmo
