Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2016
Var

Inicio
// o comando para mostrar um texto na tela é escreva ou escreval(pula linha)

escreva("Não pulei linha")

escreval("Pulei uma linha")


Fimalgoritmo
