Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor    : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2016
Var


Inicio

   //procedimentos
   //são métodos sem retorno e podem ter variáveis próprias (locais) e
   //parametros
   
   procedimento multiplicar(x,y: real)
   var n1, n2, result : real
   inicio
   n1<-x
   n2<-y
   result<-n1*n2
   escreval("A multiplicao é: ", result)
   fimprocedimento
   
   multiplicar(20, 30)
   


Fimalgoritmo
