Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/03/2016
Var
// Os tipos de dados possíveis no VisuaG são
numero : inteiro //numeros inteiros ex: 1
porcentagem : real //numeros com casa decimais ex: 1.1
texto : caracter //string, cadeia de variaveis ex: "Julio"
falsoVerdadeiro : logico //VERDADEIRO ou FALSO


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo
