algoritmo "semnome"
// Função :
// Autor :
// Data : 18/04/2016
// Seção de Declarações
var
preco, novoPreco, perc : real
i : inteiro
inicio

enquanto (preco <= 0) faca
   escreval("Digite o valor do carro")
   leia(preco)
   limpatela
fimenquanto

escreval("Pagamento a vista com 20% de desconto R$ ", ((preco*20)/100):5:2)

para i de 6 ate 60 passo 6 faca
perc<-i/2
    novoPreco<-preco*


fimpara




fimalgoritmo
